# Introduction to Pandas with Financial Data

> Business Administration of NTPU, 2026-03-13

[郭耀仁](https://hahow.in/@tonykuoyj) | <yaojenkuo@ntu.edu.tw>

## 關於講者：郭耀仁

- 資料科學的專業講師，在 [Hahow 好學校](https://hahow.in/@tonykuoyj?tr=tonykuoyj) 開設七堂線上課程，共有七千多名學生。
- 實體課程：台大工商管理學系、台大共同教育中心、台大資工系統訓練班、中華電信學院。
- 講授過台灣銀行、兆豐銀行、星展銀行、華南銀行與玉山銀行的 Python 教育訓練/工作坊。
- 在擔任專業講師前曾於酷澎（Coupang）、賽仕電腦（SAS）與中國信託（CTBC）任職；畢業自台灣大學商學研究所。
- 閒暇時喜歡長跑與桌球。

## 關於 Pandas

## 什麼是 Pandas

> Pandas 是 Python 處理表格式資料（Tabular data）的第三方模組，它創造了 `Index`、`Series` 與 `DataFrame` 的資料結構類別，讓 Python 在面對表格式資料時能夠用更直覺的觀念操作。

來源：<https://github.com/pandas-dev/pandas>

## （沒什麼用的冷知識）Pandas 跟熊貓「沒有關係」

1. **Pan**el(自從版本 0.20.0 之後棄用)
2. **Da**taFrame
3. **S**eries

![](https://media.giphy.com/media/46Zj6ze2Z2t4k/giphy.gif)

來源：<https://media.giphy.com/media/46Zj6ze2Z2t4k/giphy.gif>

## 根據說明文件的範例載入

來源：<https://pandas.pydata.org/docs/user_guide/10min.html>

In [1]:
import pandas as pd

## 可以透過兩個屬性檢查版本號與安裝路徑

- `__version__` 屬性檢查版本號。
- `__file__` 屬性檢查安裝路徑。

In [2]:
print(pd.__version__)
print(pd.__file__)

2.1.4
/Users/kuoyaojen/miniconda3/envs/datascience/lib/python3.11/site-packages/pandas/__init__.py

## 入門 Pandas 的第一步就是掌握 `Index`、`ndarray`、`Series` 與 `DataFrame` 四個資料結構類別彼此之間的關係

- `Series` 由 `Index` 與 `ndarray` 組合而成。
- `DataFrame` 由數個共享同一個 `Index` 的 `Series` 組合而成。

## Pandas 的 `DataFrame` 類別

使用 `pd.DataFrame()` 函數創造 `DataFrame` 類別的實例。

- 輸入以欄為基準（Column-based）的資料內容。
- 輸入以列為基準（Row-based）的資料內容。

## 輸入以欄為基準（Column-based）的資料內容

In [3]:
movie_df = pd.DataFrame()
movie_df["title"] = ["The Shawshank Redemption", "The Dark Knight", "Schindler's List", "Forrest Gump", "Inception"]
movie_df["imdb_rating"] = [9.3, 9.0, 8.9, 8.8, 8.7]
movie_df["release_year"] = [1994, 2008, 1993, 1994, 2010]
print(movie_df)
print(type(movie_df))

                      title  imdb_rating  release_year
0  The Shawshank Redemption          9.3          1994
1           The Dark Knight          9.0          2008
2          Schindler's List          8.9          1993
3              Forrest Gump          8.8          1994
4                 Inception          8.7          2010
<class 'pandas.core.frame.DataFrame'>

## 輸入以列為基準（Row-based）的資料內容

In [4]:
movies = [
    {"title": "The Shawshank Redemption", "imdb_rating": 9.3, "release_year": 1994},
    {"title": "The Dark Knight", "imdb_rating": 9.0, "release_year": 2008},
    {"title": "Schindler's List", "imdb_rating": 8.9, "release_year": 1993},
    {"title": "Forrest Gump", "imdb_rating": 8.8, "release_year": 1994},
    {"title": "Inception", "imdb_rating": 8.7, "release_year": 2010},
]
movie_df = pd.DataFrame(movies)
print(movie_df)
print(type(movie_df))

                      title  imdb_rating  release_year
0  The Shawshank Redemption          9.3          1994
1           The Dark Knight          9.0          2008
2          Schindler's List          8.9          1993
3              Forrest Gump          8.8          1994
4                 Inception          8.7          2010
<class 'pandas.core.frame.DataFrame'>

## Jupyter Notebook 針對 `DataFrame` 類別有特別的顯示外觀

In [5]:
movie_df

                      title  imdb_rating  release_year
0  The Shawshank Redemption          9.3          1994
1           The Dark Knight          9.0          2008
2          Schindler's List          8.9          1993
3              Forrest Gump          8.8          1994
4                 Inception          8.7          2010

## `DataFrame` 的基礎屬性

- `DataFrame.dtypes` 資料類別。
- `DataFrame.shape` 外型。
- `DataFrame.index` 取出列標籤（row labels）部分。  
- `DataFrame.columns` 取出欄標籤（column labels）的部分。

In [6]:
print(movie_df.dtypes)
print(movie_df.shape)
print(movie_df.index)
print(movie_df.columns)

title            object
imdb_rating     float64
release_year      int64
dtype: object
(5, 3)
RangeIndex(start=0, stop=5, step=1)
Index(['title', 'imdb_rating', 'release_year'], dtype='object')

## `DataFrame` 由數個 `Series` 共享同一個 `Index` 組成

In [7]:
print(type(movie_df.index))
print(type(movie_df["title"]))
print(type(movie_df["imdb_rating"]))
print(type(movie_df["release_year"]))

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

## `DataFrame` 的基礎方法

- `DataFrame.head(n)` 檢視前 `n` 列。
- `DataFrame.tail(n)` 檢視後 `n` 列。
- `DataFrame.describe()`  檢視數值欄位的描述性統計。
- `DataFrame.info()` 檢視詳細資訊。

## 檢視前 `n` 列、後 `n` 列

- `DataFrame.head(n)` 檢視前 `n` 列。
- `DataFrame.tail(n)` 檢視後 `n` 列。

In [8]:
movie_df.head(3)

                      title  imdb_rating  release_year
0  The Shawshank Redemption          9.3          1994
1           The Dark Knight          9.0          2008
2          Schindler's List          8.9          1993

In [9]:
movie_df.tail(2)

          title  imdb_rating  release_year
3  Forrest Gump          8.8          1994
4     Inception          8.7          2010

## `DataFrame.describe()` 檢視數值欄位的描述性統計

In [10]:
movie_df.describe()

       imdb_rating  release_year
count     5.000000      5.000000
mean      8.940000   1999.800000
std       0.230217      8.438009
min       8.700000   1993.000000
25%       8.800000   1994.000000
50%       8.900000   1994.000000
75%       9.000000   2008.000000
max       9.300000   2010.000000

## `DataFrame.info()` 檢視詳細資訊

In [11]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         5 non-null      object
 1   imdb_rating   5 non-null      float64
 2   release_year  5 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

## 現代資料科學：以程式設計做資料科學的應用

![](images/r4ds.png)

來源：[R for Data Science](https://r4ds.had.co.nz/introduction.html)

## 資料科學的應用場景

- Import 資料的載入。
- Tidy 資料清理。
- Transform 資料外型與類別的轉換。
- Visualise 探索性分析。
- Model 分析與預測模型。
- Communicate 溝通分享。

## 常見的來源資料格式

1. 純文字檔案。
2. 試算表。
3. 關聯式資料庫中的資料表。

## 什麼是純文字檔案

只有文字所構成的電腦檔案，不包含字型的樣式或者段落標記，能夠使用最簡單的文字編輯器（例如 Windows 的「記事本」、macOS 的 TextEdit）直接開啟檢視。

## 更適合程式設計與資料科學的文字編輯器

- [Visual Studio Code](https://code.visualstudio.com/)
- [Atom](https://atom.io/)
- [Sublime Text](https://www.sublimetext.com/)
- [Notepad ++(for Windows only)](https://notepad-plus-plus.org/)

## 不同格式的純文字檔案

- 非結構化的純文字檔案。
- JSON(JavaScript Object Notation)
- 特定符號分隔的純文字檔案。

## 特定符號分隔的純文字檔案

- 透過特定符號分隔欄位的結構化資料。
- 常見的有逗號（`,`）、分號（`;`）、Tab 鍵（`\t`）等。
- 最廣泛使用的是逗號，因此有特定的副檔名 `.csv` 意指逗號分隔值（Comma-separated values）。

## 下載金融數據 `.csv`

- `listing_dates.csv`
- `market_caps.csv`
- `top_ranking_stocks.csv`

In [12]:
!wget -Nq https://raw.githubusercontent.com/datainpoint/classroom-hahow-learn-python-with-stock-data/refs/heads/main/datasets/listing_dates.csv
!wget -Nq https://raw.githubusercontent.com/datainpoint/classroom-hahow-learn-python-with-stock-data/refs/heads/main/datasets/market_caps.csv
!wget -Nq https://raw.githubusercontent.com/datainpoint/classroom-hahow-learn-python-with-stock-data/refs/heads/main/datasets/top_ranking_stocks.csv

## 使用 `pd.read_csv()` 函數載入

In [13]:
listing_dates_csv = pd.read_csv("listing_dates.csv")
listing_dates_csv.head() # just show the first 5 rows

    ticker listing_date
0  6515.TW   2021-01-20
1  7769.TW   2025-11-27
2  6669.TW   2019-03-27
3  3653.TW   2009-11-18
4  2059.TW   2008-06-25

In [14]:
market_caps_csv = pd.read_csv("market_caps.csv")
market_caps_csv.head() # just show the first 5 rows

    ticker    market_cap recorded_on
0  6515.TW  1.973299e+11  2026-03-10
1  7769.TW  7.385019e+11  2026-03-10
2  6669.TW  7.359295e+11  2026-03-10
3  3653.TW  5.063208e+11  2026-03-10
4  2059.TW  2.916088e+11  2026-03-10

In [15]:
top_ranking_stocks_csv = pd.read_csv("top_ranking_stocks.csv")
top_ranking_stocks_csv.head() # just show the first 5 rows

    ticker stock   price recorded_on
0  6515.TW    穎崴  5475.0  2026-03-10
1  7769.TW    鴻勁  4105.0  2026-03-10
2  6669.TW    緯穎  3960.0  2026-03-10
3  3653.TW    健策  3495.0  2026-03-10
4  2059.TW    川湖  3060.0  2026-03-10

## 什麼是試算表

> 試算表是類比紙本計算表格的電腦軟體，由許多列與欄所構成的儲存格，其中可以存放數值、算式或文字。常見的試算表軟體有 Microsoft Excel、macOS Numbers 與 Google Sheets

來源：<https://en.wikipedia.org/wiki/Spreadsheet>

## 下載金融數據 `.xlsx`

In [16]:
!wget -Nq https://raw.githubusercontent.com/datainpoint/classroom-hahow-learn-python-with-stock-data/refs/heads/main/datasets/trading_volumes.xlsx

## 使用 `pd.read_excel()` 函數載入

In [17]:
excel_file_path = "trading_volumes.xlsx"
trading_volumes_xlsx = pd.read_excel(excel_file_path)
trading_volumes_xlsx.head() # just show the first 5 rows

    traded_on  volume
0  2026-02-10  450098
1  2026-02-11  369387
2  2026-02-23  715349
3  2026-02-24  539129
4  2026-02-25  504387

## 試算表檔案的組成

- 試算表的檔案為一個活頁簿（Workbook）、活頁簿中可以有多個試算表（Spreadsheets）
- `pd.read_excel()` 函數預設讀取第零張試算表（左邊數來第一張）。
- 可以透過 `pd.ExcelFile.sheet_names` 屬性檢視活頁簿中有幾個試算表。

In [18]:
excel_file = pd.ExcelFile(excel_file_path)
sheet_names = excel_file.sheet_names
print(len(sheet_names))

200

## 指定參數 `sheet_name` 載入特定試算表

In [19]:
pd.read_excel(excel_file, sheet_name=sheet_names[1])

     traded_on   volume
0   2026-02-10  1618566
1   2026-02-11  2208403
2   2026-02-23  1581221
3   2026-02-24  1228106
4   2026-02-25  1046444
5   2026-02-26  7828250
6   2026-03-02  2558920
7   2026-03-03  2175107
8   2026-03-04  2191569
9   2026-03-05  1225012
10  2026-03-06   830315
11  2026-03-09  1397982
12  2026-03-10  1034421

## 指定參數 `sheet_name` 亦能夠接受整數輸入，左邊數來第幾張試算表（由零開始）

In [20]:
pd.read_excel(excel_file_path, sheet_name=1)

     traded_on   volume
0   2026-02-10  1618566
1   2026-02-11  2208403
2   2026-02-23  1581221
3   2026-02-24  1228106
4   2026-02-25  1046444
5   2026-02-26  7828250
6   2026-03-02  2558920
7   2026-03-03  2175107
8   2026-03-04  2191569
9   2026-03-05  1225012
10  2026-03-06   830315
11  2026-03-09  1397982
12  2026-03-10  1034421

## 什麼是關聯式資料庫中的資料表

> 關聯式資料庫（Relational database）是基於關聯模型所建構的資料庫，是儲存在電腦中的資料集合。一個資料庫中通常會有多個資料表（Table）能夠藉助集合運算（Set operation）等數學方法來處理資料表之間的操作和關聯，也能夠用來表示現實世界中的商業邏輯，並能夠接受結構化查詢語言 SQL 來進行檢索和操作。

來源：<https://en.wikipedia.org/wiki/Relational_database>

## 下載金融數據 `.db`

In [21]:
!wget -Nq https://raw.githubusercontent.com/datainpoint/classroom-hahow-learn-python-with-stock-data/refs/heads/main/datasets/trading_volumes.db

## 如何載入關聯式資料庫中的資料表

- 使用 `sqlite3.connect()` 函數建立與資料庫的連線。
- 運用 `str` 儲存結構化查詢語言 SQL
- 使用 `pd.read_sql()` 函數載入。
- 使用 `Connection.close()` 關閉資料庫連線。

```python
import sqlite3
import pandas as pd

connection = sqlite3.connect("PATH/TO/SQLITE/DATABASE")
query = """SQL QUERY"""
pd.read_sql(query, connection)
connection.close()
```

## 關聯式資料庫 `trading_volumes.db` 的資料表

- `tickers`
- `volumes`

In [22]:
import sqlite3

db_file_path = "trading_volumes.db"
connection = sqlite3.connect(db_file_path)
query = """SELECT * FROM tickers;"""
tickers_table = pd.read_sql(query, connection)
connection.close()
tickers_table.head()

   id     ticker
0   1    0057.TW
1   2  00631L.TW
2   3   1264.TWO
3   4   1268.TWO
4   5    1476.TW

In [23]:
connection = sqlite3.connect(db_file_path)
query = """SELECT * FROM volumes;"""
volumes_table = pd.read_sql(query, connection)
connection.close()
volumes_table.head()

   ticker_id   traded_on  volume
0        127  2026-02-10  450098
1        127  2026-02-11  369387
2        127  2026-02-23  715349
3        127  2026-02-24  539129
4        127  2026-02-25  504387

## Pandas 使用更直觀的概念操作資料

- 如何定義「更直觀」？
    - 像操作試算表一般（Spreadsheet-like）
    - 像使用結構化查詢語言一般（SQL-like）

## 基礎的資料框操作

- 選擇欄位。
- 篩選資料列。
- 排序資料框。
- 分組聚合欄位。
- 調整列標籤與欄標籤。

## 選擇欄位

```python
df[column_name]
df[[column_names]]
```

## 篩選資料列

```python
df[booling_index]
```

## 排序資料框

```python
df.sort_index()
df.sort_values(column_names)
```

## 分組聚合欄位

```python
df.groupby(column_name)[column_name].aggregate_method()
```

## 調整列標籤與欄標籤

```python
df = df.reset_index()
df.columns = column_names
```

## 進階的資料框操作

- 迭代資料框的列或欄。
- 處理未定義值。
- 轉置資料框。
- 單純合併資料框。
- 關聯資料框。

## 迭代資料框的列或欄

```python
for column_label, series in df.iteritems():
    # iter columns

for row_label, series in df.iterrows():
    # iter rows
```

## 處理未定義值

## 常見未定義值的處理方式

```python
# 檢查未定義值是否存在
df[column_name].isna()
df[column_name].notna()
# 刪除未定義值
df.dropna()
# 填補未定義值
df.fillna()
df.ffill()
df.bfill()
```

## 轉置資料框

## `pd.melt()` 函數可以將資料框由寬格式轉換為長格式

- `id_vars` 參數指定非數值的欄位。
- `value_vars` 參數指定數值的欄位，預設指定 `id_vars` 以外的所有欄位。
- `var_name` 參數指定變數類別的欄標籤。
- `value_name` 參數指定數值的欄標籤。

```python
pd.melt(df, id_vars, value_vars, var_name, value_name)
```

## `DataFrame.pivot()` 可以將資料框由長格式轉換為寬格式

- `index` 參數指定非數值的欄位。
- `columns` 參數指定變數類別，對應 `pd.melt()` 的 `var_name`
- `values` 參數指定數值，對應 `pd.melt()` 的 `value_name`

```python
df.pivot(index, columns, values)
```

## 單純合併資料框

## 使用 `pd.concat()` 函數單純垂直與水平合併

- 將要合併的資料框以結構傳入。
- 參數預設 `axis=0` 單純垂直合併。 
- 預設不會重設列標籤，可以指定參數 `ignore_index=True` 重設列標籤。

```python
pd.concat((df_1, df_2, ...), axis=0, ignore_index=True)
```

## 關聯資料框

資料框的列標籤、欄標籤都是 `Index` 類別，由於 `Index` 類別支援集合運算的特性，因此資料框之間能夠進行觀測值與變數的交集、聯集的運算，實踐類似資料庫的關聯式模型，包含與交集對應的內部連接（Inner join）、左外部連接（Left join）、右外部連接（Right join）以及與聯集對應的全外部連接（Full join）。

## 四種連接

1. 內部連接（Inner join），保留兩個關聯資料框交集的觀測值。
2. 左外部連接（Left join），保留左資料框所有的觀測值以及兩個關聯資料框交集的觀測值。
3. 右外部連接（Right join），保留右資料框所有的觀測值以及兩個關聯資料框交集的觀測值。
4. 全外部連接（Full join），保留兩個關聯資料框聯集的觀測值。

## 關聯資料框的函數與方法

- 使用 `pd.merge()` 函數利用欄標籤進行四種連接。
- 使用 `DataFrame.join()` 利用列標籤進行四種連接。

```python
pd.merge(df_1, df_2, how="inner")
df_1.join(df_2, how="left")
```